# Generated by Django 2.2.6 on 2019-11-29 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('living', models.CharField(max_length=50)),
                ('Hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employee_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('employee_message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
