# Generated by Django 2.2.6 on 2019-11-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_client',
            name='user_id',
        ),
    ]
