# Generated by Django 2.2.6 on 2019-11-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_client_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_client',
            name='user_id',
        ),
    ]
