# Generated by Django 2.2.6 on 2019-11-27 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('camera_used', models.CharField(max_length=20)),
                ('Event_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('videoField', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('is_finished_pay', models.BooleanField(default=True)),
            ],
        ),
    ]
