# Generated by Django 2.2.6 on 2019-11-27 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_title', models.CharField(blank=True, max_length=200)),
                ('event_photos', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('CEO_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Event_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
