# Generated by Django 2.2.6 on 2019-11-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='CEO_photo',
            field=models.ImageField(blank=True, default='/static/img/kops/ceo.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
